# Generated by Django 4.2.14 on 2024-08-16 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_remove_skill_employee_delete_employee_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('emp_no', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_start_date', models.DateField(blank=True, null=True)),
                ('emp_end_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('status', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_dep', to='master.department')),
                ('designation', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_des', to='master.designation')),
                ('location', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_loc', to='master.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='master.employee')),
            ],
        ),
    ]
