# Generated by Django 4.2.14 on 2024-08-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_employee_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
